
variables:
  serverFarmName: "my-website"
  bluePath: "c:\\inetpub\\wwwroot\\myapp.blue"
  greenPath: "c:\\inetpub\\wwwroot\\myapp.green"
  bluePort: 8888
  greenPort: 9999
  warmUpPath: "/index.html"

stages:
  - stage: deployProd
    displayName: Deploy to Production
    jobs:
      - deployment: deployProd
        displayName: Deploy to Production
        environment: "my-website-prod"
        strategy:
          runOnce:
            preDeploy:
              steps:
                - task: PowerShell@2
                  inputs:
                    filePath: 'scripts/Get-StagingAndLive.ps1'
                    arguments: '-serverFarmName $(serverFarmName) -bluePath $(bluePath) -greenPath $(greenPath)'
            deploy:
              steps:
                - powershell: write-host Deploying...