
variables:
  serverFarmName: "my-website"
  bluePath: "c:\\inetpub\\wwwroot\\mywebsite.blue"
  greenPath: "c:\\inetpub\\wwwroot\\mywebsite.green"
  bluePort: 8888
  greenPort: 9999
  warmUpPath: "/index.html"

stages:
  - stage: deployProd
    displayName: Deploy to Production
    jobs:
      - deployment: deployProd
        displayName: Deploy to Production
        environment:
          name: "my-website-prod"
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  inputs:
                    filePath: 'scripts/Get-StagingAndLive.ps1'
                    arguments: '-serverFarmName $(serverFarmName) -bluePath $(bluePath) -greenPath $(greenPath)'
                - powershell: write-host "Deploying to Staging $env:server"
                  env:
                    server: $(StagingServer)
                - task: PowerShell@2
                  inputs:
                    filePath: 'scripts/WarmUp-StagingInstance.ps1'
                    arguments: '-stagingServer $(stagingServer) -bluePort $(bluePort) -greenPort $(greenPort) -serverFarmName $(serverFarmName) -warmUpPath $(warmUpPath)'