
variables:
  serverFarmName: "my-website"
  bluePath: "c:\\inetpub\\wwwroot\\mywebsite.blue"
  greenPath: "c:\\inetpub\\wwwroot\\mywebsite.green"
  bluePort: 8888
  greenPort: 9999
  warmUpPath: "index.html"

stages:
  - stage: deployProd
    displayName: Deploy to Production
    jobs:
      - deployment: deployProd
        displayName: Deploy to Production
        environment:
          name: "my-website-prod"
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  displayName: Get Staging and Live Instances
                  inputs:
                    filePath: 'scripts/Get-StagingAndLive.ps1'
                    arguments: '-serverFarmName "$(serverFarmName)" -bluePath "$(bluePath)" -greenPath "$(greenPath)"'
                - powershell: write-host "Deploying to Staging $env:server"
                  displayName: Deploy to Staging Instance
                  env:
                    server: $(stagingServer)
                - task: PowerShell@2
                  displayName: Warm Up Staging Instance $(stagingServer)
                  inputs:
                    filePath: 'scripts/WarmUp-StagingInstance.ps1'
                    arguments: '-instanceToWarm "$(stagingServer)" -bluePort "$(bluePort)" -greenPort "$(greenPort)" -serverFarmName "$(serverFarmName)" -warmUpPath "$(warmUpPath)"'
                - task: PowerShell@2
                  displayName: Bring Up Staging Instance
                  inputs:
                    filePath: 'scripts/Enable-StagingInstance.ps1'
                    arguments: '-serverFarmName "$(serverFarmName)" -stagingInstance "$(stagingServer)"'
                - task: PowerShell@2
                  displayName: Drain Live Instance
                  inputs:
                    filePath: 'scripts/Drain-LiveInstance.ps1'
                    arguments: '-serverFarmName "$(serverFarmName)" -liveInstance "$(liveServer)"'
                - task: PowerShell@2
                  displayName: Post Deployment Health Checks
                  inputs:
                    filePath: 'scripts/Run-PostDeployHealthChecks.ps1'
                    arguments: '-serverFarmName "$(serverFarmName)" -oldStagingSite "$(stagingServer)" -oldLiveSite "$(liveServer)"'